#!/usr/bin/env bash
#
# Build the three static libraries LinBPQ.exe links, with mingw-w64.
#
# Upstream ships MSVC-built zlibstat.lib, libconfig.lib and miniupnpc.lib.
# They carry MSVC C-runtime references that the mingw-w64 linker cannot
# resolve, so they are rebuilt from source at versions matching the headers
# upstream bundles.
#
# usage: build-deps.sh DEPS_DIR    (libraries land in DEPS_DIR/lib)
set -euo pipefail

DEPS="${1:?usage: build-deps.sh DEPS_DIR}"
CC="${CC:-i686-w64-mingw32-gcc}"
AR="${AR:-i686-w64-mingw32-ar}"
CFLAGS=(-std=gnu17 -O2)

ZLIB=zlib-1.3.1
ZLIB_URL=https://github.com/madler/zlib/releases/download/v1.3.1/$ZLIB.tar.gz
ZLIB_SHA=9a93b2b7dfdac77ceba5a558a580e74667dd6fede4585b91eefb60f03b72df23
LIBCONFIG=libconfig-1.7.3
LIBCONFIG_URL=https://github.com/hyperrealm/libconfig/releases/download/v1.7.3/$LIBCONFIG.tar.gz
LIBCONFIG_SHA=545166d6cac037744381d1e9cc5a5405094e7bfad16a411699bcff40bbb31ee7
# 2.2.6 = MINIUPNPC_API_VERSION 17, the miniupnpc.h upstream bundles.
MINIUPNPC=miniupnpc-2.2.6
MINIUPNPC_URL=https://miniupnp.tuxfamily.org/files/$MINIUPNPC.tar.gz
MINIUPNPC_SHA=37fcd91953508c3e62d6964bb8ffbc5d47f3e13481fa54e6214fcc68704c66f1

if [ -f "$DEPS/lib/libz.a" ] && [ -f "$DEPS/lib/libconfig.a" ] \
   && [ -f "$DEPS/lib/libminiupnpc.a" ]; then
    exit 0
fi

mkdir -p "$DEPS/src" "$DEPS/lib"
cd "$DEPS/src"

fetch() {
    local name="$1" url="$2" sha="$3"
    [ -f "$name.tar.gz" ] || curl -sSLf -o "$name.tar.gz" "$url"
    echo "$sha  $name.tar.gz" | shasum -a 256 -c --quiet - \
        || { echo "build-deps: checksum mismatch for $name" >&2; exit 1; }
    rm -rf "$name"
    tar xzf "$name.tar.gz"
}

fetch "$ZLIB" "$ZLIB_URL" "$ZLIB_SHA"
fetch "$LIBCONFIG" "$LIBCONFIG_URL" "$LIBCONFIG_SHA"
fetch "$MINIUPNPC" "$MINIUPNPC_URL" "$MINIUPNPC_SHA"

# zlib: upstream's bundled zconf.h is configured with ZLIB_WINAPI (stdcall
# exports such as inflate@8), so the library must be too.
(
    cd "$ZLIB"
    for f in adler32 compress crc32 deflate gzclose gzlib gzread gzwrite \
             infback inffast inflate inftrees trees uncompr zutil; do
        "$CC" "${CFLAGS[@]}" -DZLIB_WINAPI -c "$f.c"
    done
    "$AR" rcs "$DEPS/lib/libz.a" ./*.o
)

# libconfig: the tarball ships the generated parser and scanner.
# wincompat.c defines fsync() on every Windows compiler, but wincompat.h
# declares it only for MSVC.
(
    cd "$LIBCONFIG/lib"
    echo 'int fsync(int fd);' > fsync_decl.h
    for f in libconfig grammar scanner scanctx strbuf strvec wincompat util; do
        "$CC" "${CFLAGS[@]}" -DLIBCONFIG_STATIC -include fsync_decl.h \
            -I. -c "$f.c"
    done
    "$AR" rcs "$DEPS/lib/libconfig.a" ./*.o
)

# miniupnpc: miniupnpcstrings.h is normally generated by its build system.
(
    cd "$MINIUPNPC"
    sed -e 's|OS/version|MS-Windows|' \
        -e 's|MINIUPNPC_VERSION_STRING "version"|MINIUPNPC_VERSION_STRING "2.2.6"|' \
        miniupnpcstrings.h.in > src/miniupnpcstrings.h
    for f in minissdpc miniwget minixml igd_desc_parse minisoap miniupnpc \
             upnpreplyparse upnpcommands upnperrors connecthostport \
             portlistingparse receivedata addr_is_reserved; do
        "$CC" "${CFLAGS[@]}" -DMINIUPNP_STATICLIB -D_WIN32_WINNT=0x0601 \
            -Iinclude -Isrc -c "src/$f.c" -o "src/$f.o"
    done
    "$AR" rcs "$DEPS/lib/libminiupnpc.a" src/*.o
)
